[window]
decorations = "none"
option_as_alt = "Both"
dynamic_padding = true

[general]
live_config_reload = true

[font]
normal = {family = "ZedMono Nerd Font" }
# normal = { family = "JetBrainsMono Nerd Font"}
size = 27

[colors.primary]
# background = "#080808"
# background = "#111111"
background = "#0E1415"
# background = "#1C1C1C"
# background = "#121212"
# background = "#1C1C1C"
# background = "#1C1C1C"

