[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"   # or "OnlyLeft" / "OnlyRight" if you want to preserve compose on one side
# blur = true
# opacity = 0.8

[general]
live_config_reload = true

[font]
normal = {family = "ZedMono Nerd Font" }
# normal = {family = "Fira Code" }
size = 23

[colors.primary]
background = '#141415'

[[keyboard.bindings]]
chars = "\u001Bp"
key = "p"
mods = "Alt"
