config-version = 2
enable-normalization-opposite-orientation-for-nested-containers = false
enable-normalization-flatten-containers = false
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

after-startup-command = [
	'exec-and-forget /opt/homebrew/bin/sketchybar'
]

[mode.main.binding]
alt-o = 'exec-and-forget ~/.config/scripts/choos.sh'
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-m = 'macos-native-fullscreen'
alt-e = 'layout tiles horizontal vertical'
alt-shift-space = 'layout floating tiling'

alt-shift-h = 'resize smart -50'
alt-shift-l = 'resize smart +50'

alt-a = 'workspace 1'
alt-s = 'workspace 2'
alt-d = 'workspace 3'
alt-f = 'workspace 4'
alt-g = 'workspace 5'
alt-j = 'workspace 6'
alt-k = 'workspace 7'
alt-semicolon= 'workspace 8'

alt-shift-a = 'move-node-to-workspace 1'
alt-shift-s = 'move-node-to-workspace 2'
alt-shift-d = 'move-node-to-workspace 3'
alt-shift-f = 'move-node-to-workspace 4'
alt-shift-g = 'move-node-to-workspace 5'
alt-shift-j = 'move-node-to-workspace 6'
alt-shift-k = 'move-node-to-workspace 7'
alt-shift-semicolon = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.photobooth'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.facetime'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 4'
