font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
background 			 #141415
italic_font      auto
bold_italic_font auto
font_size        25

term xterm-kitty
shell_integration no-cursor

# Cursor settings
cursor_shape     block
# cursor_beam_thickness 1.5
# cursor_blink_interval 0
# cursor_trail 3

# Scrollback
scrollback_lines 10000

hide_window_decorations titlebar-only
sync_to_monitor  yes
allow_remote_control yes
update_check_interval 24

