github.com:
    git_protocol: https
    users:
        user-sbd:
            oauth_token: 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
    user: user-sbd
    oauth_token: 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
