#!/usr/bin/env bash

CATEGORIES=("STOP" "STUDY" "CODE" "LEARN")

selected=$(printf '%s\n' "${CATEGORIES[@]}" \
    | fzf --reverse)

[[ $? -eq 0 && -n "$selected" ]] || exit 0

tmux set -g status-interval 1 2>/dev/null

if [[ "$selected" == "STOP" ]]; then
    timew stop >/dev/null 2>&1
		tmux set -g status-right ""
else
    timew start "$selected" >/dev/null 2>&1
		tmux source-file ~/.config/tmux/tmux.conf
fi
