set-option -g prefix C-a
bind r source-file ~/.config/tmux/tmux.conf 
unbind C-b
set -g renumber-windows on  
set -g base-index 1
set -g escape-time 0       
set -g status-style "bg=default"
set -g status-position top
set -g status-justify absolute-centre
set -g status-left " #S"
set -g status-left-length "20"
set -g status-right ""
set -g status-interval 5
setw -g window-status-current-style 'fg=magenta bold '
setw -g mode-keys vi
bind | split-pane -v
bind Space switch-client -l
bind "'" split-pane -h
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5
bind -n M-l resize-pane -R 5
bind c new-window -c "#{pane_current_path}"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind x kill-pane 
bind o neww "~/.config/scripts/zath.sh"
bind k run-shell "~/.config/scripts/unused.sh"
bind G run-shell "~/.config/scripts/git.sh"
bind f neww "~/.config/scripts/tmux.sh"
bind W neww "~/.config/scripts/time.sh"
bind g display-popup -d '#{pane_current_path}' -w80% -h100% -E lazygit
bind E show-environment -g
