thm_bg="#222436"
thm_fg="#c8d3f5"
thm_cyan="#86e1fc"
thm_black="#1b1d2b"
thm_gray="#3a3f5a"
thm_magenta="#c099ff"
thm_pink="#ff757f"
thm_red="#ff757f"
thm_green="#c3e88d"
thm_yellow="#ffc777"
thm_blue="#82aaff"
thm_orange="#ff9e64"
thm_black4="#444a73"

set-option -g prefix C-a
bind r source-file ~/.config/tmux/tmux.conf 
unbind C-b
unbind i
set -g renumber-windows on  
set -g base-index 1
set -g escape-time 0       
set -g status-style "bg=default"
set -g status-position top
set -g status-justify absolute-centre
set -g status-left " #S"
set -g status-left-length "20"
set -g status-right ""
set -g status-interval 5

set -g window-status-style "fg=white"
set -g window-status-current-style "fg=blue bold"

setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#I:#W'

setw -g mode-keys vi
bind "'" split-pane -v
bind Space switch-client -l
bind | split-pane -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind x kill-pane 
bind k run-shell "~/.config/scripts/unused.sh"
bind G run-shell "~/.config/scripts/git.sh"
bind o neww "~/.config/scripts/zath.sh"
bind f neww "~/.config/scripts/tmux.sh"
bind w neww "~/.config/scripts/time.sh"
bind m neww "~/.config/scripts/man.sh"
bind g neww -n git -c "#{pane_current_path}" "lazygit"
bind E show-environment -g
