set-option -g prefix C-a
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-interval 1
set -g status on
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=#cdcdcd,bg=default"
set -g status-justify absolute-centre
set -g message-style "fg=#252530,bg=#aeaed1"
set -g status-left "#[fg=#cdcdcd,bg=default] #S "
set -g status-right ""
setw -g window-status-separator " "
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
set -g status-style 'fg=white'
setw -g window-status-current-style fg=white,bold,bg=blue
set -g focus-events on
# set-option -g status-position top
# bind-key -T copy-mode-vi 'v' send -X begin-selection

setw -g mode-keys vi
bind "'" split-pane -h
bind Space switch-client -l
bind '\' split-pane -h
bind - split-pane -v

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind-key -r h resize-pane -L 5
bind-key -r l resize-pane -R 5
bind-key -r k resize-pane -U 5
bind-key -r j resize-pane -D 5

bind c new-window -c "#{pane_current_path}"
bind a split-window -h \; send-keys 'ai' C-m
bind r source-file ~/.config/tmux/tmux.conf 
bind x kill-pane 
bind f neww "~/.config/scripts/tmux.sh"
bind k run-shell "~/.config/scripts/unused.sh"
bind g run-shell "~/.config/scripts/git.sh"
bind t neww "~/.config/scripts/time"

